version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
